#!/usr/bin/python -u
#
# akrun
#
# This file run a series of VASP and Alamode jobs to calcualte thermal
# conductivity.
#
# Copyright (c) 2022 Masato Ohnishi
#
# This file is distributed under the terms of the MIT license.
# Please see the file 'LICENCE.txt' in the root directory
# or http://opensource.org/licenses/mit-license.php for information.
#

from auto_kappa.cui.ak_scripts import main

if __name__ == "__main__":
    main()

